In [82]:
from pathlib import Path
import numpy as np
import pandas as pd
from datatools.fixture import setup_dummy_data
# test_tool
# source = setup_dummy_data(5)

# put data into this source folder
source = "./tool-tracking-data/"
import torch

In [2]:
from datatools import MeasurementDataReader, Measurement, MeasurementSeries, Action
mdr = MeasurementDataReader(source=source)

In [3]:
q = mdr.query(query_type=Measurement)

In [4]:
from datatools import Tool, Config, MeasurementSeries, Measurement, DataTypes, Action
from datatools import ACC, GYR, MAG, MIC, POS, VEL

mytool = "electric_screwdriver"
# mytool = "pneumatic_screwdriver"
# mytool = "pneumatic_rivet_gun"
#mytool = "test_tool"

data_dict = q.filter_by(Tool == mytool).get()

[INFO] Preparing data from:
  tool-tracking-data\electric_screwdriver\pythagoras-10-20200716
  tool-tracking-data\electric_screwdriver\pythagoras-10-20200716
  tool-tracking-data\electric_screwdriver\pythagoras-10-20200716
  tool-tracking-data\electric_screwdriver\pythagoras-10-20200716


[INFO] Read data:  25%|██▌       | 4/16 [00:00<00:00, 38.41it/s, file=ACC-04-102.291.csv]

[WARN] The mean sampling rate from the filename (tool-tracking-data\electric_screwdriver\pythagoras-10-20200716\ACC-01-102.291.csv) and from the timestamps differ by 0.001Hz

[WARN] The mean sampling rate from the filename (tool-tracking-data\electric_screwdriver\pythagoras-10-20200716\ACC-02-102.291.csv) and from the timestamps differ by 0.001Hz

[WARN] The mean sampling rate from the filename (tool-tracking-data\electric_screwdriver\pythagoras-10-20200716\ACC-03-102.291.csv) and from the timestamps differ by 0.001Hz

[WARN] The mean sampling rate from the filename (tool-tracking-data\electric_screwdriver\pythagoras-10-20200716\ACC-04-102.291.csv) and from the timestamps differ by 0.001Hz

[WARN] The mean sampling rate from the filename (tool-tracking-data\electric_screwdriver\pythagoras-10-20200716\GYR-01-102.291.csv) and from the timestamps differ by 0.001Hz

[WARN] The mean sampling rate from the filename (tool-tracking-data\electric_screwdriver\pythagoras-10-20200716\GYR-02-102.29

[INFO] Read data:  56%|█████▋    | 9/16 [00:00<00:00, 37.82it/s, file=MAG-01-155.087.csv]

[WARN] The mean sampling rate from the filename (tool-tracking-data\electric_screwdriver\pythagoras-10-20200716\MAG-01-155.087.csv) and from the timestamps differ by 0.001Hz

[WARN] The mean sampling rate from the filename (tool-tracking-data\electric_screwdriver\pythagoras-10-20200716\MAG-02-154.679.csv) and from the timestamps differ by 0.001Hz

[WARN] The mean sampling rate from the filename (tool-tracking-data\electric_screwdriver\pythagoras-10-20200716\MAG-03-154.871.csv) and from the timestamps differ by 0.002Hz

[WARN] The mean sampling rate from the filename (tool-tracking-data\electric_screwdriver\pythagoras-10-20200716\MAG-04-154.967.csv) and from the timestamps differ by 0.001Hz



[INFO] Read annotation: 100%|██████████| 16/16 [00:02<00:00,  5.86it/s, file=data-04.annotation]

[INFO] Finished with 4 measurement(s).


In [5]:
data_dict.keys()

dict_keys(['01', '02', '03', '04'])

In [6]:
len(data_dict['04'])

5

In [7]:
data_dict['01'].keys()

dict_keys(['acc', 'gyr', 'mag', 'mic', 'classes'])

In [8]:
print(len(data_dict['03']["acc"]))
print(len(data_dict['03']["gyr"]))
print(len(data_dict['03']["mag"]))
print(len(data_dict['03']["mic"]))
print(len(data_dict['03']["classes"]))

33620
33620
50902
2629280
8


In [9]:
data_dict['01']["acc"].keys()

Index(['time [s]', 'acceleration x-axis [m/s^2]',
       'acceleration y-axis [m/s^2]', 'acceleration z-axis [m/s^2]', 'label'],
      dtype='object')

In [11]:
from seglearn.base import TS_Data
from seglearn.pipe import Pype
from fhgutils import Segment, contextual_recarray_dtype, filter_ts_data
from datatools import to_ts_data

In [12]:
window_length=0.4 # unit in s
overlap = 0.5 # unit in percent

# clean and window data
data_dict = mdr.query().filter_by(Tool == mytool).get()
Xt, Xc, y = to_ts_data(data_dict, contextual_recarray_dtype)

X = TS_Data(Xt, Xc)
pipe = Pype([
    ('segment', Segment(window_length=window_length, overlap=overlap, enforce_size=True, n=len(np.unique(Xc.desc))))
])

X_trans, y_trans = pipe.fit_transform(X, y)

[INFO] Preparing data from:
  tool-tracking-data\electric_screwdriver\pythagoras-10-20200716
  tool-tracking-data\electric_screwdriver\pythagoras-10-20200716
  tool-tracking-data\electric_screwdriver\pythagoras-10-20200716
  tool-tracking-data\electric_screwdriver\pythagoras-10-20200716


[INFO] Read data:  31%|███▏      | 5/16 [00:00<00:00, 41.20it/s, file=GYR-01-102.291.csv]

[WARN] The mean sampling rate from the filename (tool-tracking-data\electric_screwdriver\pythagoras-10-20200716\ACC-01-102.291.csv) and from the timestamps differ by 0.001Hz

[WARN] The mean sampling rate from the filename (tool-tracking-data\electric_screwdriver\pythagoras-10-20200716\ACC-02-102.291.csv) and from the timestamps differ by 0.001Hz

[WARN] The mean sampling rate from the filename (tool-tracking-data\electric_screwdriver\pythagoras-10-20200716\ACC-03-102.291.csv) and from the timestamps differ by 0.001Hz

[WARN] The mean sampling rate from the filename (tool-tracking-data\electric_screwdriver\pythagoras-10-20200716\ACC-04-102.291.csv) and from the timestamps differ by 0.001Hz

[WARN] The mean sampling rate from the filename (tool-tracking-data\electric_screwdriver\pythagoras-10-20200716\GYR-01-102.291.csv) and from the timestamps differ by 0.001Hz

[WARN] The mean sampling rate from the filename (tool-tracking-data\electric_screwdriver\pythagoras-10-20200716\GYR-02-102.29

[INFO] Read data:  62%|██████▎   | 10/16 [00:00<00:00, 37.53it/s, file=MAG-02-154.679.csv]


[WARN] The mean sampling rate from the filename (tool-tracking-data\electric_screwdriver\pythagoras-10-20200716\MAG-02-154.679.csv) and from the timestamps differ by 0.001Hz

[WARN] The mean sampling rate from the filename (tool-tracking-data\electric_screwdriver\pythagoras-10-20200716\MAG-03-154.871.csv) and from the timestamps differ by 0.002Hz

[WARN] The mean sampling rate from the filename (tool-tracking-data\electric_screwdriver\pythagoras-10-20200716\MAG-04-154.967.csv) and from the timestamps differ by 0.001Hz



[INFO] Read annotation: 100%|██████████| 16/16 [00:02<00:00,  6.10it/s, file=data-04.annotation]


[INFO] Finished with 4 measurement(s).
[INFO] segment ['acc' 'gyr' 'mag' 'mic'] together
[INFO] segment ['acc' 'gyr' 'mag' 'mic'] together
[INFO] segment ['acc' 'gyr' 'mag' 'mic'] together
[INFO] segment ['acc' 'gyr' 'mag' 'mic'] together
Segment: 100%|██████████| 29060/29060 [00:00<00:00, 59208.55it/s]


In [50]:
print(len(X_trans)/4)

7265.0


In [64]:
print(len(X_trans[5:7]))

2


In [97]:
print(X_trans[3].ts_data)

[[ 1.59422628e+09  7.00000000e+00]
 [ 1.59422628e+09 -1.00000000e+00]
 [ 1.59422628e+09 -9.00000000e+00]
 ...
 [ 1.59422628e+09  9.00000000e+00]
 [ 1.59422628e+09  1.40000000e+01]
 [ 1.59422628e+09  1.70000000e+01]]


In [36]:
len(y_trans)

29060

In [110]:
Xt_acc, Xc_acc, y_acc = filter_ts_data(X_trans, y_trans)

In [111]:
len(Xt_acc)

29060

In [58]:
y_trans[20740]

array([8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 7., 7., 7., 7.,
       7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7.,
       7., 7., 7., 7., 7., 7., 7.])

In [51]:
from fhgutils import filter_labels, one_label_per_window, summarize_labels


In [106]:
def get_data(idx, exclude_time=True):
    idx = idx * 4 
    
    x_acc, x_gyr, x_mag, x_mic = X_trans[idx:idx+4].ts_data

    if exclude_time:
        x_acc = x_acc[:, 1:] 
        x_gyr = x_gyr[:, 1:]
        x_mag = x_mag[:, 1:]
        x_mic = x_mic[:, 1:] 
    
    y_window = y_trans[idx:idx+4]
    
    return x_acc, x_gyr, x_mag, x_mic, y_window

In [99]:
len(get_data(4))

5

In [100]:
get_data(4)[3].shape

(3200, 2)

In [101]:
a, g, m, mi, y = get_data(4, True)

In [102]:
a.shape

(41, 3)

In [103]:
agmmi = np.concatenate([a, g], axis=1)

In [104]:
agmmi.shape

(41, 6)

In [105]:
agmmi[0]

array([-4.48509252,  0.75922297,  9.2839081 , -0.39663217, -0.03106879,
        1.46171328])

In [113]:
import torch
from torch.utils.data import Dataset
import numpy as np
from datatools import MeasurementDataReader, Measurement, Tool
from datatools import to_ts_data
from fhgutils import Segment, contextual_recarray_dtype, filter_ts_data
from fhgutils import filter_labels, one_label_per_window
from seglearn.base import TS_Data
from seglearn.pipe import Pype
import torch.nn.functional as F

In [92]:
y[3]

array([8., 8., 8., ..., 8., 8., 8.], shape=(3200,))

In [94]:
one_label_per_window(y=[y[3]])

flattened 1 labels: [8]


[8]

In [95]:
agmmi

array([[ 1.59422628e+09, -4.48509252e+00,  7.59222969e-01,
         9.28390810e+00,  1.59422628e+09, -3.96632168e-01,
        -3.10687861e-02,  1.46171328e+00],
       [ 1.59422628e+09, -4.63321063e+00,  7.75730214e-01,
         9.39502086e+00,  1.59422628e+09, -3.87588243e-01,
        -1.94567297e-02,  1.40727686e+00],
       [ 1.59422628e+09, -4.73794176e+00,  7.99411858e-01,
         9.45501236e+00,  1.59422628e+09, -3.85990937e-01,
        -8.77064177e-03,  1.36173277e+00],
       [ 1.59422628e+09, -4.72536157e+00,  7.99762965e-01,
         9.44459176e+00,  1.59422628e+09, -3.80299400e-01,
        -2.01645514e-03,  1.30636009e+00],
       [ 1.59422628e+09, -4.90541448e+00,  8.30796110e-01,
         9.38995107e+00,  1.59422628e+09, -3.80391581e-01,
        -1.43397443e-03,  1.25032418e+00],
       [ 1.59422628e+09, -4.92109515e+00,  7.57104024e-01,
         9.35494600e+00,  1.59422628e+09, -3.81364700e-01,
        -5.75979986e-03,  1.18671791e+00],
       [ 1.59422628e+09, -5.049363

In [96]:
a

array([[ 1.59422628e+09, -4.48509252e+00,  7.59222969e-01,
         9.28390810e+00],
       [ 1.59422628e+09, -4.63321063e+00,  7.75730214e-01,
         9.39502086e+00],
       [ 1.59422628e+09, -4.73794176e+00,  7.99411858e-01,
         9.45501236e+00],
       [ 1.59422628e+09, -4.72536157e+00,  7.99762965e-01,
         9.44459176e+00],
       [ 1.59422628e+09, -4.90541448e+00,  8.30796110e-01,
         9.38995107e+00],
       [ 1.59422628e+09, -4.92109515e+00,  7.57104024e-01,
         9.35494600e+00],
       [ 1.59422628e+09, -5.04936336e+00,  8.13975419e-01,
         9.35373168e+00],
       [ 1.59422628e+09, -5.08008281e+00,  7.99619483e-01,
         9.30035389e+00],
       [ 1.59422628e+09, -5.19471233e+00,  7.85863960e-01,
         9.21782037e+00],
       [ 1.59422628e+09, -5.25811595e+00,  7.85566400e-01,
         9.15511203e+00],
       [ 1.59422628e+09, -5.27735253e+00,  6.42449007e-01,
         8.94356111e+00],
       [ 1.59422628e+09, -5.12261963e+00,  5.47597924e-01,
      

In [124]:
class ToolTrackingDataset(Dataset):
    def __init__(self, source_path, tool_name="electric_screwdriver", window_length=0.4, overlap=0.5, exclude_time=True):
        self.source_path = source_path
        self.exclude_time = exclude_time
        
        mdr = MeasurementDataReader(source=source_path)
        
        print(f"[INFO] Querying data for tool: {tool_name}...")
        self.data_dict = mdr.query().filter_by(Tool == tool_name).get()

        print("[INFO] Converting to TS Data...")
        Xt, Xc, y = to_ts_data(self.data_dict, contextual_recarray_dtype)
        
        print(f"[INFO] Segmenting data (Window: {window_length}s, Overlap: {overlap})...")
        X_obj = TS_Data(Xt, Xc)
                
        pipe = Pype([
            ('segment', Segment(window_length=window_length, 
                                overlap=overlap, 
                                enforce_size=True, 
                                n=len(np.unique(Xc.desc))))
        ])
        
        self.X_trans, self.y_trans = pipe.fit_transform(X_obj, y)

    def __len__(self):
        return int(len(self.y_trans)/4)

    def __getitem__(self, idx):
        idx = idx * 4 
    
        x_acc, x_gyr, x_mag, x_mic = self.X_trans[idx:idx+4].ts_data

        if self.exclude_time:
            x_acc = x_acc[:, 1:] 
            x_gyr = x_gyr[:, 1:]
            x_mag = x_mag[:, 1:]
            x_mic = x_mic[:, 1:] 
        
        y_window = self.y_trans[idx:idx+4]
        
        return x_acc, x_gyr, x_mag, x_mic, y_window

In [125]:
source_folder = "./tool-tracking-data/"

dataset = ToolTrackingDataset(
    source_path=source_folder,
    tool_name="electric_screwdriver",
    window_length=0.4,
    overlap=0.5,
    exclude_time=True
)

[INFO] Querying data for tool: electric_screwdriver...
[INFO] Preparing data from:
  tool-tracking-data\electric_screwdriver\pythagoras-10-20200716
  tool-tracking-data\electric_screwdriver\pythagoras-10-20200716
  tool-tracking-data\electric_screwdriver\pythagoras-10-20200716
  tool-tracking-data\electric_screwdriver\pythagoras-10-20200716


[INFO] Read data:  25%|██▌       | 4/16 [00:00<00:00, 37.86it/s, file=ACC-04-102.291.csv]

[WARN] The mean sampling rate from the filename (tool-tracking-data\electric_screwdriver\pythagoras-10-20200716\ACC-01-102.291.csv) and from the timestamps differ by 0.001Hz

[WARN] The mean sampling rate from the filename (tool-tracking-data\electric_screwdriver\pythagoras-10-20200716\ACC-02-102.291.csv) and from the timestamps differ by 0.001Hz

[WARN] The mean sampling rate from the filename (tool-tracking-data\electric_screwdriver\pythagoras-10-20200716\ACC-03-102.291.csv) and from the timestamps differ by 0.001Hz

[WARN] The mean sampling rate from the filename (tool-tracking-data\electric_screwdriver\pythagoras-10-20200716\ACC-04-102.291.csv) and from the timestamps differ by 0.001Hz

[WARN] The mean sampling rate from the filename (tool-tracking-data\electric_screwdriver\pythagoras-10-20200716\GYR-01-102.291.csv) and from the timestamps differ by 0.001Hz

[WARN] The mean sampling rate from the filename (tool-tracking-data\electric_screwdriver\pythagoras-10-20200716\GYR-02-102.29

[INFO] Read data:  56%|█████▋    | 9/16 [00:00<00:00, 35.97it/s, file=MAG-01-155.087.csv]

[WARN] The mean sampling rate from the filename (tool-tracking-data\electric_screwdriver\pythagoras-10-20200716\MAG-01-155.087.csv) and from the timestamps differ by 0.001Hz

[WARN] The mean sampling rate from the filename (tool-tracking-data\electric_screwdriver\pythagoras-10-20200716\MAG-02-154.679.csv) and from the timestamps differ by 0.001Hz

[WARN] The mean sampling rate from the filename (tool-tracking-data\electric_screwdriver\pythagoras-10-20200716\MAG-03-154.871.csv) and from the timestamps differ by 0.002Hz

[WARN] The mean sampling rate from the filename (tool-tracking-data\electric_screwdriver\pythagoras-10-20200716\MAG-04-154.967.csv) and from the timestamps differ by 0.001Hz



[INFO] Read annotation: 100%|██████████| 16/16 [00:02<00:00,  6.00it/s, file=data-04.annotation]


[INFO] Finished with 4 measurement(s).
[INFO] Converting to TS Data...
[INFO] Segmenting data (Window: 0.4s, Overlap: 0.5)...
[INFO] segment ['acc' 'gyr' 'mag' 'mic'] together
[INFO] segment ['acc' 'gyr' 'mag' 'mic'] together
[INFO] segment ['acc' 'gyr' 'mag' 'mic'] together
[INFO] segment ['acc' 'gyr' 'mag' 'mic'] together
Segment: 100%|██████████| 29060/29060 [00:00<00:00, 63674.76it/s]


In [129]:
len(dataset[7000])

5

In [132]:
dataset[1][-1]

[array([8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8.,
        8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8.,
        8., 8., 8., 8., 8., 8., 8.]),
 array([8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8.,
        8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8.,
        8., 8., 8., 8., 8., 8., 8.]),
 array([8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8.,
        8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8.,
        8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8.,
        8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]),
 array([8., 8., 8., ..., 8., 8., 8.], shape=(3200,))]

In [155]:
valid = 0
invalid = 0

for i in range(len(dataset)):
    if i % 100 == 0:
        print(f"Processing window {i}/{len(dataset)}")
    print(i)
    y_window = dataset[i][-1]
    print(y_window)
    print(len(y_window))
    labels = [one_label_per_window([y_window[j]])[0] for j in range(4)]
    if all(label == labels[0] for label in labels):
        valid += 1
    else:
        invalid += 1

Processing window 0/7265
0
[array([8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8.,
       8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8.,
       8., 8., 8., 8., 8., 8., 8.]), array([8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8.,
       8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8.,
       8., 8., 8., 8., 8., 8., 8.]), array([8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8.,
       8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8.,
       8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8.,
       8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]), array([8., 8., 8., ..., 8., 8., 8.], shape=(3200,))]
4
flattened 1 labels: [8]
flattened 1 labels: [8]
flattened 1 labels: [8]
flattened 1 labels: [8]
1
[array([8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8.,
       8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8.,
       8., 8., 8

IndexError: list index out of range

In [149]:
dataset[197][-1][-1]

array([3., 3., 3., ..., 8., 8., 8.], shape=(3200,))

In [147]:
[one_label_per_window([dataset[197][-1][j]])[0] for j in range(4)]

flattened 1 labels: [3]
flattened 1 labels: [3]
flattened 1 labels: [3]
flattened 0 labels: []


IndexError: list index out of range

In [150]:
one_label_per_window([dataset[197][-1][-1]])

flattened 0 labels: []


[]

In [151]:
d = {}

for i in dataset[197][-1][-1]:
    v = d.setdefault(i, 0)
    v += 1
    d[i] = v


In [152]:
d

{np.float64(3.0): 1600, np.float64(8.0): 1600}

In [156]:
valid, invalid

(197, 0)

In [206]:
class ToolTrackingDataset(Dataset):
    def __init__(self, source_path, tool_name="electric_screwdriver", window_length=0.4, overlap=0.5, exclude_time=True):
        self.source_path = source_path
        self.exclude_time = exclude_time
        
        mdr = MeasurementDataReader(source=source_path)
        
        print(f"[INFO] Querying data for tool: {tool_name}...")
        self.data_dict = mdr.query().filter_by(Tool == tool_name).get()

        print("[INFO] Converting to TS Data...")
        Xt, Xc, y = to_ts_data(self.data_dict, contextual_recarray_dtype)
        
        print(f"[INFO] Segmenting data (Window: {window_length}s, Overlap: {overlap})...")
        X_obj = TS_Data(Xt, Xc)
                
        pipe = Pype([
            ('segment', Segment(window_length=window_length, 
                                overlap=overlap, 
                                enforce_size=True, 
                                n=len(np.unique(Xc.desc))))
        ])
        
        self.X_trans, self.y_trans = pipe.fit_transform(X_obj, y)

        # --- 3. FILTERING LOGIC (Your Request) ---
        print(f"[INFO] Filtering ambiguous windows (Total raw groups: {len(self.y_trans)//4})...")
        self.valid = []

        for i in range(0, len(self.y_trans), 4):
            y_window = self.y_trans[i:i+4]

            try:
                labels = [one_label_per_window([y_window[j]])[0] for j in range(4)]
                print(labels)
                print("size:", len(set(labels)))
                if len(set(labels)) == 1:
                    print("[DEBUG]")
                    self.valid.append(i)
                    
            except Exception as e:
                continue

        print(f"[INFO] Filtering complete. Valid groups: {self.valid}")
        print(f"[INFO] Filtering complete. Valid groups: {len(self.valid)}")

    def __len__(self):
        return len(self.valid)

    def __getitem__(self, idx):
        idx = self.valid[idx]
    
        x_acc, x_gyr, x_mag, x_mic = self.X_trans[idx:idx+4].ts_data

        if self.exclude_time:
            x_acc = x_acc[:, 1:] 
            x_gyr = x_gyr[:, 1:]
            x_mag = x_mag[:, 1:]
            x_mic = x_mic[:, 1:] 
        
        y_window = self.y_trans[idx:idx+4]
        
        return x_acc, x_gyr, x_mag, x_mic, y_window[0][0]

In [207]:
source_folder = "./tool-tracking-data/"

dataset = ToolTrackingDataset(
    source_path=source_folder,
    tool_name="electric_screwdriver",
    window_length=0.4,
    overlap=0.5,
    exclude_time=True
)

[INFO] Querying data for tool: electric_screwdriver...
[INFO] Preparing data from:
  tool-tracking-data\electric_screwdriver\pythagoras-10-20200716
  tool-tracking-data\electric_screwdriver\pythagoras-10-20200716
  tool-tracking-data\electric_screwdriver\pythagoras-10-20200716
  tool-tracking-data\electric_screwdriver\pythagoras-10-20200716


[INFO] Read data:  31%|███▏      | 5/16 [00:00<00:00, 40.55it/s, file=GYR-01-102.291.csv]

[WARN] The mean sampling rate from the filename (tool-tracking-data\electric_screwdriver\pythagoras-10-20200716\ACC-01-102.291.csv) and from the timestamps differ by 0.001Hz

[WARN] The mean sampling rate from the filename (tool-tracking-data\electric_screwdriver\pythagoras-10-20200716\ACC-02-102.291.csv) and from the timestamps differ by 0.001Hz

[WARN] The mean sampling rate from the filename (tool-tracking-data\electric_screwdriver\pythagoras-10-20200716\ACC-03-102.291.csv) and from the timestamps differ by 0.001Hz

[WARN] The mean sampling rate from the filename (tool-tracking-data\electric_screwdriver\pythagoras-10-20200716\ACC-04-102.291.csv) and from the timestamps differ by 0.001Hz

[WARN] The mean sampling rate from the filename (tool-tracking-data\electric_screwdriver\pythagoras-10-20200716\GYR-01-102.291.csv) and from the timestamps differ by 0.001Hz

[WARN] The mean sampling rate from the filename (tool-tracking-data\electric_screwdriver\pythagoras-10-20200716\GYR-02-102.29

[INFO] Read data:  62%|██████▎   | 10/16 [00:00<00:00, 33.53it/s, file=MAG-02-154.679.csv]

[WARN] The mean sampling rate from the filename (tool-tracking-data\electric_screwdriver\pythagoras-10-20200716\MAG-01-155.087.csv) and from the timestamps differ by 0.001Hz

[WARN] The mean sampling rate from the filename (tool-tracking-data\electric_screwdriver\pythagoras-10-20200716\MAG-02-154.679.csv) and from the timestamps differ by 0.001Hz

[WARN] The mean sampling rate from the filename (tool-tracking-data\electric_screwdriver\pythagoras-10-20200716\MAG-03-154.871.csv) and from the timestamps differ by 0.002Hz

[WARN] The mean sampling rate from the filename (tool-tracking-data\electric_screwdriver\pythagoras-10-20200716\MAG-04-154.967.csv) and from the timestamps differ by 0.001Hz



[INFO] Read annotation: 100%|██████████| 16/16 [00:02<00:00,  5.85it/s, file=data-04.annotation]


[INFO] Finished with 4 measurement(s).
[INFO] Converting to TS Data...
[INFO] Segmenting data (Window: 0.4s, Overlap: 0.5)...
[INFO] segment ['acc' 'gyr' 'mag' 'mic'] together
[INFO] segment ['acc' 'gyr' 'mag' 'mic'] together
[INFO] segment ['acc' 'gyr' 'mag' 'mic'] together
[INFO] segment ['acc' 'gyr' 'mag' 'mic'] together
Segment: 100%|██████████| 29060/29060 [00:00<00:00, 69608.96it/s]
[INFO] Filtering ambiguous windows (Total raw groups: 7265)...
flattened 1 labels: [8]
flattened 1 labels: [8]
flattened 1 labels: [8]
flattened 1 labels: [8]
[8, 8, 8, 8]
size: 1
[DEBUG]
flattened 1 labels: [8]
flattened 1 labels: [8]
flattened 1 labels: [8]
flattened 1 labels: [8]
[8, 8, 8, 8]
size: 1
[DEBUG]
flattened 1 labels: [8]
flattened 1 labels: [8]
flattened 1 labels: [8]
flattened 1 labels: [8]
[8, 8, 8, 8]
size: 1
[DEBUG]
flattened 1 labels: [8]
flattened 1 labels: [8]
flattened 1 labels: [8]
flattened 1 labels: [8]
[8, 8, 8, 8]
size: 1
[DEBUG]
flattened 1 labels: [8]
flattened 1 labels: [

In [208]:
len(dataset)

7141

In [209]:
dataset[0]

(array([[-5.877378  ,  1.322051  ,  8.612491  ],
        [-5.81989653,  1.29330976,  8.59332943],
        [-5.75962318,  1.24230908,  8.57014775],
        [-5.67889097,  1.21746263,  8.56938   ],
        [-5.48350376,  1.21188   ,  8.41825245],
        [-5.42591265,  1.23846681,  8.35849331],
        [-5.30720967,  1.29817759,  8.33327202],
        [-5.18268454,  1.27927157,  8.30552778],
        [-5.05876173,  1.42567306,  8.26228635],
        [-4.91898259,  1.43020264,  8.21863291],
        [-4.83879847,  1.47447276,  8.22493579],
        [-4.84187027,  1.54826683,  8.24758904],
        [-4.74338303,  1.54838852,  8.30351054],
        [-4.7157439 ,  1.57450339,  8.30602671],
        [-4.63512489,  1.63866364,  8.35097615],
        [-4.59522287,  1.68785702,  8.38263138],
        [-4.55331515,  1.7252836 ,  8.4059737 ],
        [-4.55266945,  1.78136953,  8.42218192],
        [-4.55009912,  1.80880658,  8.48491077],
        [-4.59628629,  1.87178836,  8.57098461],
        [-4.66188046

In [204]:
dataset[0][-1][0][0]

np.float64(8.0)

In [211]:
X_trans[0].ts_data.shape

(41, 4)

In [217]:
ref_data = X_trans[0 : 0+4].ts_data

In [219]:
ref_data[2].shape

(62, 4)